repos:
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: src/.venv/bin/nbstripout
        language: system
        files: '^src/.*\.ipynb$'
        types: [file]
