repos:
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: scripts/nbstripout-hook.sh
        language: script
        files: '^src/.*\.ipynb$'
        types: [file]
